name: Merge Master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.4']

    name: Upload coverage report
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, xdebug
          tools: composer:v2
          coverage: xdebug

      - name: Composer Check
        run: composer validate

      - name: Install
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Coverage Report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          export CODECOVERAGE=1 && vendor/bin/phpunit --coverage-clover=clover.xml
          php-coveralls --coverage_clover=clover.xml -v
